#!/usr/bin/env python3

import os, sys, json


def log(s=""):
    print(s, file=sys.stderr)


if any(arg == "--describe" for arg in sys.argv):
    log("List bots that can be run with bot-run (json)")
    sys.exit()

bots_dir = os.environ["BOTS_DIR"]
bots = [
    os.path.basename(f.path)
    for f in os.scandir(bots_dir)
    if f.is_dir() and os.path.exists(os.path.join(f, "default.nix"))
]

print(json.dumps(bots))
