#!/usr/bin/env python3

import os, sys, json, subprocess


def log(s=""):
    print(s, file=sys.stderr)


if any(arg == "--describe" for arg in sys.argv):
    log("Run a bot connected to the development homeserver")
    sys.exit()

if len(sys.argv) != 2:
    log("Usage: bot-run <bot>")

bot_list_output = subprocess.check_output("bot-list")
bots = json.loads(bot_list_output)

# TODO
