#!/usr/bin/env python3

import os, sys, json, subprocess


def log(s=""):
    print(s, file=sys.stderr)


def read_secret():
    out = sys.stdout
    sys.stdout = sys.stderr
    secret = input("Secret: ")
    sys.stdout = out
    return secret


if any(arg == "--describe" for arg in sys.argv):
    log("Run a bot connected to the development homeserver")
    sys.exit()

if len(sys.argv) != 2:
    log("Usage: bot-run <bot>")
    sys.exit(1)


bot = sys.argv[1]
flake = os.environ["FLAKE_DIR"]
domain = os.environ["DOMAIN"]
conduit_port = os.environ["CONDUIT_PORT"]

if not flake:
    log("Environment variable FLAKE_DIR is not defined")
    sys.exit(2)
if not domain:
    log("Environment variable DOMAIN is not defined")
    sys.exit(2)
if not conduit_port:
    log("Environment variable CONDUIT_PORT is not defined")
    sys.exit(4)

bot_list_output = subprocess.check_output("bot-list")
bots = json.loads(bot_list_output)

if bot not in bots:
    log(f'Could not find bot "{bot}".\nValid bots: {bots}')
    sys.exit(4)

secret = read_secret()

password = subprocess.check_output(
    ["gen-passwd", secret, f"bot.{bot}"], text=True
).rstrip()
homeserver = f"http://localhost:{conduit_port}"
command = ["nix", "run", f"{flake}#bots.{bot}"]
data_dir = f"tmp/bot/{bot}"

env = os.environ.copy()
env["BOT_DATA_DIR"] = data_dir
env["BOT_HOMESERVER"] = f"http://localhost:{conduit_port}"
env["BOT_USERNAME"] = f"bot.{bot}"
env["BOT_PASSWORD"] = password

log(f'\nRunning bot "{bot}"...\n')
subprocess.run(command, stderr=sys.stderr, stdout=sys.stdout, env=env)
