#!/usr/bin/env python3

import sys, random

COMMAND = "@conduit:war-room.chat: create-user"
PASSWORD_PREFIX = "change-me-"


def log(s=""):
    print(s, file=sys.stderr)


def read_secret():
    out = sys.stdout
    sys.stdout = sys.stderr
    secret = input("Secret: ")
    sys.stdout = out
    return secret


if len(sys.argv) < 2:
    log("Usage: create-user <username>...")
    sys.exit()

if any(arg == "--describe" for arg in sys.argv):
    log("Generate Conduit admin command(s) to create user(s)")
    sys.exit()

secret = read_secret()
log()

for username in sys.argv[1:]:
    random.seed(secret + username)
    password = PASSWORD_PREFIX + str(random.randbytes(4).hex())
    print(" ".join([COMMAND, username, password]))
