#!/usr/bin/env python3

import sys, random


def log(s=""):
    print(s, file=sys.stderr)


if any(arg == "--describe" for arg in sys.argv):
    log("Generate a secure password based on a secret")
    sys.exit()

if len(sys.argv) != 3:
    log("Usage: gen-passwd <secret> <username>")
    sys.exit(1)

secret, username = sys.argv[1:]
random.seed(secret + username)
password = str(random.randbytes(16).hex())

print(password)
