#!/usr/bin/env python3

import sys, random, subprocess, os

COMMAND = "@conduit:war-room.chat: create-user"
PASSWORD_PREFIX = "change-me-"


def log(s=""):
    print(s, file=sys.stderr)


def read_secret():
    out = sys.stdout
    sys.stdout = sys.stderr
    secret = input("Secret: ")
    sys.stdout = out
    return secret


if len(sys.argv) < 2:
    log("Usage: create-user <username>...")
    sys.exit(1)

if any(arg == "--describe" for arg in sys.argv):
    log("Generate Dendrite admin command(s) to create user(s)")
    sys.exit()

secret = read_secret()
log()

for username in sys.argv[1:]:
    gen_passwd_output = subprocess.check_output(
        ["gen-passwd", secret, username], text=True
    ).rstrip()
    password = PASSWORD_PREFIX + gen_passwd_output
    command = [
        "nix",
        "shell",
        "nixpkgs#dendrite",
        "-c",
        "sudo",
        "create-account",
        "-config",
        "/run/dendrite/dendrite.yaml",
        "-username",
        f'"{username}"',
        "-password",
        f'"{password}"',
    ]
    print(" ".join(command))
